# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyry < Formula
  desc "Process supervisor for Claude Code"
  homepage "https://github.com/pyrycode/pyrycode"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.10.0/pyry_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "db8c147de7dcab46ea30db711019bd90bcebe5995dd70f5a1532a39a56722ca8"

      define_method(:install) do
        bin.install "pyry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.10.0/pyry_0.10.0_Darwin_arm64.tar.gz"
      sha256 "6b52e4340fc40bf5d228dfc1f91e2605534c61a37cc630263f3ea968bb39bf51"

      define_method(:install) do
        bin.install "pyry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.10.0/pyry_0.10.0_Linux_x86_64.tar.gz"
      sha256 "f8bd533e99abee451737f39187e43abcc809f67cbf37e5924724922a93494fcb"
      define_method(:install) do
        bin.install "pyry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.10.0/pyry_0.10.0_Linux_arm64.tar.gz"
      sha256 "15ab32e7dc2e68b23a846f93732b1e31e5257fdc0ac0da57e30641288989b6a9"
      define_method(:install) do
        bin.install "pyry"
      end
    end
  end

  def caveats
    <<~EOS
      To run pyry as a long-lived daemon, see:
        https://github.com/pyrycode/pyrycode/blob/main/docs/deployment.md
    EOS
  end

  test do
    system "#{bin}/pyry", "version"
  end
end
