# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyry < Formula
  desc "Process supervisor for Claude Code"
  homepage "https://github.com/pyrycode/pyrycode"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.9.1/pyry_0.9.1_Darwin_x86_64.tar.gz"
      sha256 "3cd6b9dc4519b0f461ac34d54112e2faf20fa932e02adf2f35db7f265914164e"

      define_method(:install) do
        bin.install "pyry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.9.1/pyry_0.9.1_Darwin_arm64.tar.gz"
      sha256 "52366bf3e6b4b08242a640f11b33597d243c2e7c0bcb186506898215edb8053f"

      define_method(:install) do
        bin.install "pyry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.9.1/pyry_0.9.1_Linux_x86_64.tar.gz"
      sha256 "76fac86f562d4c7ead7cfb0a5982ffe419131b47733f0bb6bb5de9d786c12b68"
      define_method(:install) do
        bin.install "pyry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pyrycode/pyrycode/releases/download/v0.9.1/pyry_0.9.1_Linux_arm64.tar.gz"
      sha256 "791d2e2e0fb2147f7bc511a79b01d8a9c29432dca69b2235fda38a1a951d2a11"
      define_method(:install) do
        bin.install "pyry"
      end
    end
  end

  def caveats
    <<~EOS
      To run pyry as a long-lived daemon, see:
        https://github.com/pyrycode/pyrycode/blob/main/docs/deployment.md
    EOS
  end

  test do
    system "#{bin}/pyry", "version"
  end
end
